name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code formatting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Repository Dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'damiansk',
              repo: 'DevOps-Upskill-Part-II',
              workflow_id: 'apps.yml',
              ref: 'main'
            })
        # uses: peter-evans/repository-dispatch@v3
        # with:
        #   token: ${{ secrets.PAT }}
        #   repository: damiansk/DevOps-Upskill-Part-II
        #   event-type: update-app
